# Generated by Django 5.2.14 on 2026-06-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_moderator",
            field=models.BooleanField(
                default=False,
                help_text="Może moderować forum społeczności (kolejka, zgłoszenia, akcje na wątkach).",
                verbose_name="moderator",
            ),
        ),
    ]
