# Generated by Django 5.2.14 on 2026-06-01 21:09

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_chapter_transcriptline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="tytuł")),
                ("slug", models.SlugField(max_length=220, unique=True, verbose_name="slug")),
                (
                    "mode",
                    models.CharField(
                        choices=[("online", "Online"), ("live", "Live"), ("klan", "Klan")],
                        default="online",
                        max_length=10,
                        verbose_name="tryb",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                ("starts_at", models.DateTimeField(db_index=True, verbose_name="start")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(default=0, verbose_name="czas trwania (min)"),
                ),
                (
                    "cover_image",
                    models.CharField(blank=True, max_length=400, verbose_name="okładka"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(blank=True, null=True, verbose_name="pojemność"),
                ),
                (
                    "seats_taken",
                    models.PositiveIntegerField(default=0, verbose_name="zajęte miejsca"),
                ),
                ("price_pln", models.PositiveIntegerField(default=0, verbose_name="cena (PLN)")),
                ("is_free", models.BooleanField(default=True, verbose_name="darmowy")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("published", "Opublikowany"),
                            ("canceled", "Odwołany"),
                        ],
                        default="published",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("is_featured", models.BooleanField(default=False, verbose_name="wyróżniony")),
                (
                    "recording_url",
                    models.CharField(blank=True, max_length=500, verbose_name="URL nagrania"),
                ),
                (
                    "recording_access",
                    models.CharField(
                        choices=[("none", "Publiczne"), ("klub", "Klub"), ("klan", "Klan")],
                        default="none",
                        max_length=5,
                        verbose_name="dostęp do nagrania",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(blank=True, max_length=120, verbose_name="Stripe price ID"),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_events",
                        to="catalog.creator",
                        verbose_name="prowadzący",
                    ),
                ),
            ],
            options={
                "verbose_name": "wydarzenie",
                "verbose_name_plural": "wydarzenia",
                "ordering": ["-created_at"],
                "abstract": False,
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Oczekuje na płatność"),
                            ("confirmed", "Potwierdzony"),
                            ("waitlisted", "Lista rezerwowa"),
                            ("canceled", "Anulowany"),
                        ],
                        default="confirmed",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stripe checkout session ID"
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Stripe payment intent ID"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                        verbose_name="wydarzenie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registrations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "rejestracja",
                "verbose_name_plural": "rejestracje",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["starts_at"], name="events_even_starts__b01102_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["mode", "starts_at"], name="events_even_mode_d7faa6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "starts_at"], name="events_even_status_5c3d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registration",
            index=models.Index(fields=["event", "status"], name="events_regi_event_i_c98244_idx"),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["pending", "confirmed", "waitlisted"])),
                fields=("event", "user"),
                name="uniq_active_registration_event_user",
            ),
        ),
    ]
