# Generated by Django 5.2.14 on 2026-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=130, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("narrator", "Narrator"),
                            ("director", "Reżyseria"),
                            ("sound", "Dźwięk"),
                            ("writer", "Scenariusz"),
                        ],
                        db_index=True,
                        default="narrator",
                        max_length=10,
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                ("avatar", models.CharField(blank=True, max_length=300)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=90, unique=True)),
                (
                    "accent",
                    models.CharField(
                        choices=[("red", "Czerwony"), ("blue", "Niebieski"), ("none", "Brak")],
                        default="none",
                        max_length=4,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=130, unique=True)),
                ("cover", models.CharField(blank=True, max_length=300)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                "ordering": ["-number"],
                "abstract": False,
            },
        ),
    ]
