# Generated by Django 5.2.14 on 2026-05-31 21:44

import django.db.models.deletion
import django.db.models.manager
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.PositiveSmallIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("title_em", models.CharField(blank=True, max_length=120)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("duration_s", models.PositiveIntegerField(default=0)),
                ("audio_url", models.CharField(blank=True, max_length=400)),
                ("poster", models.CharField(blank=True, max_length=400)),
                ("video_preview", models.CharField(blank=True, max_length=400)),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=3),
                ),
                ("plays_count", models.PositiveIntegerField(default=0)),
                ("is_true_horror", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("fiction", "Fikcja"),
                            ("inspired", "Oparte na faktach"),
                            ("doc", "Dokument"),
                        ],
                        default="fiction",
                        max_length=10,
                    ),
                ),
                ("premium", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "creators",
                    models.ManyToManyField(
                        blank=True, related_name="episodes", to="catalog.creator"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episodes",
                        to="catalog.genre",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episodes",
                        to="catalog.season",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-number"],
                "base_manager_name": "all_objects",
                "indexes": [
                    models.Index(
                        fields=["genre", "published_at"], name="catalog_epi_genre_i_2a25b5_idx"
                    ),
                    models.Index(
                        fields=["premium", "published_at"], name="catalog_epi_premium_328ce9_idx"
                    ),
                    models.Index(
                        fields=["season", "number"], name="catalog_epi_season__463ed0_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("season", "number"), name="uniq_episode_season_number"
                    )
                ],
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
