# Generated by Django 5.2.14 on 2026-05-31 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_episode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("n", models.PositiveSmallIntegerField()),
                ("key", models.CharField(max_length=40)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("time_str", models.CharField(blank=True, max_length=12)),
                ("sec", models.PositiveIntegerField(default=0)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="catalog.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["n"],
                "constraints": [
                    models.UniqueConstraint(fields=("episode", "n"), name="uniq_chapter_episode_n")
                ],
            },
        ),
        migrations.CreateModel(
            name="TranscriptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=40)),
                ("order", models.PositiveSmallIntegerField()),
                ("sec", models.PositiveIntegerField(blank=True, null=True)),
                ("speaker", models.CharField(blank=True, max_length=40)),
                (
                    "marker",
                    models.CharField(
                        blank=True,
                        choices=[("", "—"), ("sfx", "SFX"), ("chapter", "Rozdział")],
                        default="",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcript",
                        to="catalog.episode",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("episode", "order"), name="uniq_transcript_episode_order"
                    )
                ],
            },
        ),
    ]
