# Generated by Django 5.2.14 on 2026-06-01 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_chapter_transcriptline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('free', 'Próg (free)'), ('solo', 'Solo'), ('klan', 'Klan')], max_length=8, unique=True, verbose_name='kod planu')),
                ('name', models.CharField(max_length=60, verbose_name='nazwa')),
                ('price_month', models.PositiveIntegerField(verbose_name='cena miesięczna (PLN)')),
                ('price_year', models.PositiveIntegerField(help_text='Stawka za miesiąc przy rozliczeniu rocznym; total = ×12 w serializerze.', verbose_name='cena miesięczna przy rocznym (PLN)')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='waluta')),
                ('featured', models.BooleanField(default=False, verbose_name='wyróżniony')),
                ('tag', models.CharField(blank=True, max_length=40, verbose_name='tag')),
                ('badge', models.CharField(blank=True, max_length=40, verbose_name='badge')),
                ('cta_label', models.CharField(blank=True, max_length=40, verbose_name='etykieta CTA')),
                ('monthly_quota', models.PositiveIntegerField(blank=True, help_text='Liczba nie-premium odcinków/mc dla planu (free=20); null = bez limitu.', null=True, verbose_name='limit miesięczny')),
                ('features', models.JSONField(blank=True, default=list, help_text='[{ok:bool, text:str}, ...]', verbose_name='cechy')),
                ('stripe_price_id_month', models.CharField(blank=True, max_length=120, verbose_name='Stripe price id (mc)')),
                ('stripe_price_id_year', models.CharField(blank=True, max_length=120, verbose_name='Stripe price id (rok)')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
            ],
            options={
                'verbose_name': 'plan',
                'verbose_name_plural': 'plany',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatronTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('witness', 'Świadek'), ('ally', 'Sojusznik'), ('exec', 'Producent')], max_length=8, verbose_name='kod tieru')),
                ('role_label', models.CharField(max_length=40, verbose_name='etykieta roli')),
                ('title', models.CharField(max_length=80, verbose_name='tytuł')),
                ('amount', models.PositiveIntegerField(verbose_name='kwota (PLN)')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='waluta')),
                ('featured', models.BooleanField(default=False, verbose_name='wyróżniony')),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Limit patronów (paid) w sezonie; null = bez limitu.', null=True, verbose_name='liczba miejsc')),
                ('requires_application', models.BooleanField(default=False, verbose_name='wymaga aplikacji')),
                ('perks', models.JSONField(blank=True, default=list, verbose_name='benefity')),
                ('stripe_price_id', models.CharField(blank=True, max_length=120, verbose_name='Stripe price id')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patron_tiers', to='catalog.season', verbose_name='sezon')),
            ],
            options={
                'verbose_name': 'tier patronatu',
                'verbose_name_plural': 'tiery patronatu',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patronage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='kwota (PLN)')),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('paid', 'Opłacona'), ('refunded', 'Zwrócona'), ('canceled', 'Anulowana')], default='pending', max_length=10, verbose_name='status')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='anonimowo')),
                ('credit_name', models.CharField(blank=True, max_length=80, verbose_name='podpis w napisach')),
                ('anon_number', models.PositiveIntegerField(blank=True, help_text='Sekwencyjny w obrębie sezonu dla anonimów (np. „Anonim #042“).', null=True, verbose_name='numer anonima')),
                ('is_company', models.BooleanField(default=False, verbose_name='firma')),
                ('company_name', models.CharField(blank=True, max_length=120, verbose_name='nazwa firmy')),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=120, verbose_name='Stripe checkout session id')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120, verbose_name='Stripe payment intent id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patronages', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patronages', to='membership.patrontier', verbose_name='tier')),
            ],
            options={
                'verbose_name': 'patronat',
                'verbose_name_plural': 'patronaty',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('incomplete', 'Niekompletna'), ('trialing', 'Okres próbny'), ('active', 'Aktywna'), ('past_due', 'Zaległa płatność'), ('canceled', 'Anulowana'), ('expired', 'Wygasła')], default='incomplete', max_length=12, verbose_name='status')),
                ('billing_period', models.CharField(choices=[('month', 'Miesięcznie'), ('year', 'Rocznie')], max_length=5, verbose_name='okres rozliczeniowy')),
                ('period_start', models.DateTimeField(blank=True, null=True, verbose_name='początek okresu')),
                ('period_end', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='koniec okresu')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='koniec okresu próbnego')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='auto-odnawianie')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='anuluj na koniec okresu')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120, verbose_name='Stripe customer id')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120, verbose_name='Stripe subscription id')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='membership.plan', verbose_name='plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'subskrypcja',
                'verbose_name_plural': 'subskrypcje',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreePlayGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(db_index=True, help_text='Miesiąc kalendarzowy konsumpcji, format YYYY-MM.', max_length=7, verbose_name='okres (YYYY-MM)')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_play_grants', to='catalog.episode', verbose_name='odcinek')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_play_grants', to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
            options={
                'verbose_name': 'grant odtworzenia (free)',
                'verbose_name_plural': 'granty odtworzeń (free)',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'period'], name='membership__user_id_7ba737_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'episode', 'period'), name='uniq_free_grant_user_episode_period')],
            },
        ),
        migrations.AddConstraint(
            model_name='patrontier',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='uniq_patron_tier_season_code'),
        ),
        migrations.AddConstraint(
            model_name='patronage',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'paid'])), fields=('user', 'tier'), name='uniq_active_patronage_user_tier'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='membership__user_id_0c1070_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['trialing', 'active'])), fields=('user',), name='uniq_active_subscription_per_user'),
        ),
    ]
