import pytest
from django.db import IntegrityError, transaction

from accounts.tests.factories import UserFactory
from catalog.tests.factories import EpisodeFactory
from community.models import (
    Category,
    ModAction,
    ModerationAction,
    Post,
    PostStatus,
    Reaction,
    ReactionKind,
    Report,
    ReportReason,
    ReportStatus,
    Thread,
)
from community.tests.factories import (
    CategoryFactory,
    ModerationActionFactory,
    PostFactory,
    ReactionFactory,
    ReportFactory,
    ThreadFactory,
)


def test_text_choices_values():
    assert {c for c in PostStatus.values} == {"published", "pending", "flagged", "removed"}
    assert {c for c in ReactionKind.values} == {"like", "spooky", "scared", "love"}
    assert {c for c in ReportReason.values} == {
        "spam",
        "offensive",
        "spoiler",
        "offtopic",
        "other",
    }
    assert {c for c in ReportStatus.values} == {"open", "resolved", "dismissed"}
    assert {c for c in ModAction.values} == {
        "approve",
        "reject",
        "remove",
        "restore",
        "pin",
        "unpin",
        "lock",
        "unlock",
        "flag",
    }


@pytest.mark.django_db
def test_create_all_models():
    cat = CategoryFactory(name="Ogólne")
    assert cat.pk and cat.is_active is True and cat.threads_count == 0
    thread = ThreadFactory(category=cat)
    assert thread.pk and thread.is_pinned is False and thread.posts_count == 0
    assert thread.views_count == 0 and thread.last_post_at is not None
    post = PostFactory(thread=thread, is_first=True)
    assert post.pk and post.status == PostStatus.PUBLISHED
    assert post.reaction_count == 0 and post.reactions_breakdown == {}
    reaction = ReactionFactory(post=post)
    assert reaction.pk and reaction.kind == ReactionKind.LIKE
    report = ReportFactory(post=post)
    assert report.pk and report.status == ReportStatus.OPEN
    action = ModerationActionFactory(post=post)
    assert action.pk and action.action == ModAction.APPROVE


@pytest.mark.django_db
def test_category_slug_autogenerated_from_name():
    cat = Category.objects.create(name="Strefa Mgły")
    # pl_slugify maps ł→l: "Mgły" -> "mgly", not "mgy".
    assert cat.slug == "strefa-mgly"


@pytest.mark.django_db
def test_category_ordering_by_order():
    CategoryFactory(name="Trzecia", order=3)
    CategoryFactory(name="Pierwsza", order=1)
    CategoryFactory(name="Druga", order=2)
    orders = list(Category.objects.values_list("order", flat=True))
    assert orders == [1, 2, 3]


@pytest.mark.django_db
def test_thread_slug_autogenerated_from_title():
    author = UserFactory()
    cat = CategoryFactory()
    thread = Thread.objects.create(category=cat, author=author, title="Echo w Tunelu")
    assert thread.slug == "echo-w-tunelu"


@pytest.mark.django_db
def test_thread_slug_collision_gets_numeric_suffix():
    author = UserFactory()
    cat = CategoryFactory()
    t1 = Thread.objects.create(category=cat, author=author, title="Coś tam czeka")
    t2 = Thread.objects.create(category=cat, author=author, title="Coś tam czeka")
    t3 = Thread.objects.create(category=cat, author=author, title="Coś tam czeka")
    assert t1.slug == "cos-tam-czeka"
    assert t2.slug == "cos-tam-czeka-2"
    assert t3.slug == "cos-tam-czeka-3"


@pytest.mark.django_db
def test_thread_slug_unique_enforced_at_db():
    author = UserFactory()
    cat = CategoryFactory()
    ThreadFactory(slug="duplikat", category=cat, author=author)
    with pytest.raises(IntegrityError):
        Thread.all_objects.create(category=cat, author=author, title="x", slug="duplikat")


@pytest.mark.django_db
def test_thread_episode_set_null_on_delete():
    episode = EpisodeFactory()
    thread = ThreadFactory(episode=episode)
    episode.delete()  # soft-delete on Episode does not null the FK
    thread.refresh_from_db()
    assert thread.episode_id == episode.id


@pytest.mark.django_db
def test_reaction_unique_post_user_kind():
    reaction = ReactionFactory()
    with pytest.raises(IntegrityError):
        Reaction.objects.create(post=reaction.post, user=reaction.user, kind=reaction.kind)


@pytest.mark.django_db
def test_reaction_same_user_different_kind_ok():
    reaction = ReactionFactory(kind=ReactionKind.LIKE)
    Reaction.objects.create(post=reaction.post, user=reaction.user, kind=ReactionKind.SPOOKY)
    assert Reaction.objects.filter(post=reaction.post, user=reaction.user).count() == 2


@pytest.mark.django_db
def test_report_unique_reporter_post():
    report = ReportFactory()
    with pytest.raises(IntegrityError):
        Report.objects.create(
            reporter=report.reporter, post=report.post, reason=ReportReason.OFFENSIVE
        )


@pytest.mark.django_db
def test_moderation_action_ordering_newest_first():
    post = PostFactory()
    moderator = UserFactory()
    first = ModerationActionFactory(moderator=moderator, post=post, action=ModAction.FLAG)
    second = ModerationActionFactory(moderator=moderator, post=post, action=ModAction.REMOVE)
    ids = list(ModerationAction.objects.values_list("id", flat=True))
    assert ids == [second.id, first.id]


@pytest.mark.django_db
def test_thread_soft_delete():
    thread = ThreadFactory()
    pk = thread.pk
    thread.delete()
    assert not Thread.objects.filter(pk=pk).exists()
    assert Thread.all_objects.filter(pk=pk).exists()
    deleted = Thread.all_objects.get(pk=pk)
    assert deleted.is_deleted is True and deleted.deleted_at is not None


@pytest.mark.django_db
def test_post_soft_delete():
    post = PostFactory()
    pk = post.pk
    post.delete()
    assert not Post.objects.filter(pk=pk).exists()
    assert Post.all_objects.filter(pk=pk).exists()
    assert Post.all_objects.get(pk=pk).is_deleted is True


@pytest.mark.django_db
def test_post_status_default_published():
    # Model-level default applies when status not passed explicitly.
    thread = ThreadFactory()
    post = Post.objects.create(thread=thread, author=thread.author, body="x")
    assert post.status == PostStatus.PUBLISHED


@pytest.mark.django_db
def test_thread_uses_all_objects_as_base_manager():
    # Soft-deleted thread must still be reachable via _base_manager (cascade/FK safety).
    assert Thread._base_manager.model is Thread
    assert Thread._base_manager.name == "all_objects"
    assert Post._base_manager.name == "all_objects"


@pytest.mark.django_db
def test_post_thread_cascade_hard_delete():
    # Thread.all_objects hard delete (NOT soft) cascades Posts away at DB level.
    thread = ThreadFactory()
    post = PostFactory(thread=thread)
    with transaction.atomic():
        Thread.all_objects.filter(pk=thread.pk).delete()
    assert not Post.all_objects.filter(pk=post.pk).exists()
