# Generated by Django 5.2.14 on 2026-06-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60, unique=True, verbose_name="kod")),
                ("label", models.CharField(max_length=200, verbose_name="etykieta")),
                ("purpose", models.CharField(blank=True, max_length=200, verbose_name="cel")),
                (
                    "freq_label",
                    models.CharField(blank=True, max_length=100, verbose_name="czestotliwosc"),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("transactional", "Transakcyjny"),
                            ("marketing", "Marketingowy"),
                            ("notification", "Powiadomienie"),
                            ("critical", "Krytyczny"),
                        ],
                        max_length=20,
                        verbose_name="tag",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="kolejnosc")),
                ("is_active", models.BooleanField(default=True, verbose_name="aktywna")),
            ],
            options={
                "verbose_name": "kampania",
                "verbose_name_plural": "kampanie",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True, verbose_name="email")),
                (
                    "freq",
                    models.CharField(
                        choices=[
                            ("week", "Tygodniowo"),
                            ("big", "Co dwa tygodnie"),
                            ("month", "Miesiecznie"),
                        ],
                        default="week",
                        max_length=10,
                        verbose_name="czestotliwosc",
                    ),
                ),
                ("consent_at", models.DateTimeField(blank=True, null=True, verbose_name="zgoda")),
                ("is_active", models.BooleanField(default=True, verbose_name="aktywny")),
                (
                    "unsubscribe_token",
                    models.CharField(
                        blank=True, max_length=64, unique=True, verbose_name="token wypisania"
                    ),
                ),
            ],
            options={
                "verbose_name": "subskrybent",
                "verbose_name_plural": "subskrybenci",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
