# Generated by Django 5.2.14 on 2026-06-01 16:19

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_chapter_transcriptline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, verbose_name="nazwa")),
                ("slug", models.SlugField(max_length=90, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="opis")),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text='Klucz ikony lucide (np. "MessageSquare").',
                        max_length=40,
                        verbose_name="ikona",
                    ),
                ),
                (
                    "is_moderated",
                    models.BooleanField(
                        default=False,
                        help_text="True → nowe wątki/posty trafiają do kolejki (pending) przed publikacją.",
                        verbose_name="moderowana",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="kolejność")),
                ("is_active", models.BooleanField(default=True, verbose_name="aktywna")),
                (
                    "threads_count",
                    models.PositiveIntegerField(default=0, verbose_name="liczba wątków"),
                ),
            ],
            options={
                "verbose_name": "kategoria",
                "verbose_name_plural": "kategorie",
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200, verbose_name="tytuł")),
                ("slug", models.SlugField(max_length=220, unique=True, verbose_name="slug")),
                (
                    "is_pinned",
                    models.BooleanField(db_index=True, default=False, verbose_name="przypięty"),
                ),
                ("is_locked", models.BooleanField(default=False, verbose_name="zablokowany")),
                (
                    "last_post_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="ostatni post",
                    ),
                ),
                (
                    "posts_count",
                    models.PositiveIntegerField(default=0, verbose_name="liczba odpowiedzi"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="liczba wyświetleń"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="threads",
                        to="community.category",
                        verbose_name="kategoria",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="threads",
                        to="catalog.episode",
                        verbose_name="odcinek",
                    ),
                ),
            ],
            options={
                "verbose_name": "wątek",
                "verbose_name_plural": "wątki",
                "ordering": ["-created_at"],
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("body", models.TextField(verbose_name="treść")),
                ("is_first", models.BooleanField(default=False, verbose_name="post otwierający")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Opublikowany"),
                            ("pending", "Oczekuje na moderację"),
                            ("flagged", "Zgłoszony"),
                            ("removed", "Usunięty"),
                        ],
                        default="published",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "reaction_count",
                    models.PositiveIntegerField(default=0, verbose_name="liczba reakcji"),
                ),
                (
                    "reactions_breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="Denormalizacja przez signal: {kind: liczba}.",
                        verbose_name="rozkład reakcji",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autor",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="community.thread",
                        verbose_name="wątek",
                    ),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posty",
                "ordering": ["-created_at"],
                "base_manager_name": "all_objects",
            },
            managers=[
                ("objects", django.db.models.manager.Manager()),
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ModerationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Zatwierdź"),
                            ("reject", "Odrzuć"),
                            ("remove", "Usuń"),
                            ("restore", "Przywróć"),
                            ("pin", "Przypnij"),
                            ("unpin", "Odepnij"),
                            ("lock", "Zablokuj"),
                            ("unlock", "Odblokuj"),
                            ("flag", "Oznacz"),
                        ],
                        max_length=10,
                        verbose_name="akcja",
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="powód")),
                (
                    "moderator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="moderation_actions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="moderator",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="community.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="community.thread",
                        verbose_name="wątek",
                    ),
                ),
            ],
            options={
                "verbose_name": "akcja moderacyjna",
                "verbose_name_plural": "akcje moderacyjne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("like", "Lubię to"),
                            ("spooky", "Ciarki"),
                            ("scared", "Przerażenie"),
                            ("love", "Uwielbiam"),
                        ],
                        max_length=10,
                        verbose_name="rodzaj",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="community.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "reakcja",
                "verbose_name_plural": "reakcje",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [models.Index(fields=["post"], name="community_r_post_id_4fc3df_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("post", "user", "kind"), name="uniq_reaction_post_user_kind"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("offensive", "Treść obraźliwa"),
                            ("spoiler", "Spoiler"),
                            ("offtopic", "Nie na temat"),
                            ("other", "Inne"),
                        ],
                        max_length=10,
                        verbose_name="powód",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="szczegóły")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Otwarte"),
                            ("resolved", "Rozwiązane"),
                            ("dismissed", "Odrzucone"),
                        ],
                        default="open",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                ("resolution", models.TextField(blank=True, verbose_name="rozstrzygnięcie")),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_handled",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="obsłużone przez",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="community.post",
                        verbose_name="post",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="zgłaszający",
                    ),
                ),
            ],
            options={
                "verbose_name": "zgłoszenie",
                "verbose_name_plural": "zgłoszenia",
                "ordering": ["-created_at"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reporter", "post"), name="uniq_report_reporter_post"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["category", "-last_post_at"], name="community_t_categor_ca1af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["-is_pinned", "-last_post_at"], name="community_t_is_pinn_461bdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["thread", "created_at"], name="community_p_thread__aab3f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["status"], name="community_p_status_ef88a3_idx"),
        ),
    ]
