"""Task 2 — failing tests for Event/Registration models."""

import pytest
from django.db import IntegrityError

from accounts.tests.factories import UserFactory


@pytest.mark.django_db
def test_event_slug_autogenerated():
    from events.tests.factories import EventFactory

    event = EventFactory(title="Mroczna Głębia")
    assert event.slug == "mroczna-glebia"


@pytest.mark.django_db
def test_event_slug_collision_suffix():
    from events.tests.factories import EventFactory

    e1 = EventFactory(title="Ciemny Tunel")
    e2 = EventFactory(title="Ciemny Tunel")
    assert e1.slug != e2.slug
    assert e2.slug.startswith("ciemny-tunel")


@pytest.mark.django_db
def test_event_is_free_derived_from_price():
    from events.tests.factories import EventFactory

    free_event = EventFactory(price_pln=0)
    paid_event = EventFactory(price_pln=50)
    assert free_event.is_free is True
    assert paid_event.is_free is False


@pytest.mark.django_db
def test_event_base_manager_all_objects():
    from events.models import Event
    from events.tests.factories import EventFactory

    event = EventFactory()
    event.delete()  # soft-delete
    # objects (default) should not see it
    assert Event.objects.filter(pk=event.pk).count() == 0
    # all_objects should see it
    assert Event.all_objects.filter(pk=event.pk).count() == 1


@pytest.mark.django_db
def test_event_soft_delete():
    from events.models import Event
    from events.tests.factories import EventFactory

    event = EventFactory()
    pk = event.pk
    event.delete()
    obj = Event.all_objects.get(pk=pk)
    assert obj.is_deleted is True
    assert obj.deleted_at is not None


@pytest.mark.django_db
def test_registration_create():
    from events.tests.factories import RegistrationFactory

    reg = RegistrationFactory()
    assert reg.pk is not None
    assert reg.event is not None
    assert reg.user is not None


@pytest.mark.django_db
def test_registration_partial_unique_blocks_duplicate_active():
    from events.models import RegStatus
    from events.tests.factories import EventFactory, RegistrationFactory

    user = UserFactory()
    event = EventFactory()
    RegistrationFactory(event=event, user=user, status=RegStatus.CONFIRMED)
    with pytest.raises(IntegrityError):
        RegistrationFactory(event=event, user=user, status=RegStatus.CONFIRMED)


@pytest.mark.django_db
def test_registration_partial_unique_allows_canceled_then_new():
    """A canceled registration should not block a new active one."""
    from events.models import RegStatus
    from events.tests.factories import EventFactory, RegistrationFactory

    user = UserFactory()
    event = EventFactory()
    RegistrationFactory(event=event, user=user, status=RegStatus.CANCELED)
    # Should not raise
    reg2 = RegistrationFactory(event=event, user=user, status=RegStatus.CONFIRMED)
    assert reg2.pk is not None


@pytest.mark.django_db
def test_event_str():
    from events.tests.factories import EventFactory

    event = EventFactory(title="Horror Night")
    assert "Horror Night" in str(event)
